workflows:
  ios-release:
    name: iOS Unsigned IPA (archive->payload) - variphone
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean & get packages
        script: |
          set -euo pipefail
          flutter clean
          flutter pub get

      - name: Force iOS deployment target (Podfile = 13.0)
        script: |
          set -euo pipefail

          if [ ! -f "ios/Podfile" ]; then
            echo "ios/Podfile not found!"
            exit 1
          fi

          ruby -e "
            path='ios/Podfile'
            s=File.read(path)
            if s =~ /^platform :ios,/
              s = s.sub(/^platform :ios, *'[^']*'/, \"platform :ios, '13.0'\")
            else
              s = \"platform :ios, '13.0'\\n\" + s
            end
            File.write(path, s)
          "

          ruby -e "
            path='ios/Podfile'
            s=File.read(path)
            block = <<~RUBY

            post_install do |installer|
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                end
              end
            end
            RUBY
            unless s.include?('post_install do |installer|')
              s = s + block
              File.write(path, s)
            end
          "

          echo '=== Podfile platform ==='
          grep -n "^platform :ios" ios/Podfile || true

      - name: CocoaPods install
        script: |
          set -euo pipefail
          cd ios
          pod install --repo-update
          cd ..

      - name: Archive with Xcode (NO code signing)
        script: |
          set -euo pipefail

          flutter --version

          # تأكد workspace موجود (pod install يسويه)
          ls -la ios || true
          ls -la ios/Runner.xcworkspace || true

          # Archive بدون أي Signing (هذا يتجاوز طلب Development Team)
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/ios/archive/Runner.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            PROVISIONING_PROFILE=""

          echo "=== Archive contents ==="
          ls -la build/ios/archive || true

      - name: Package unsigned IPA from xcarchive (Payload)
        script: |
          set -euo pipefail

          APP="build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app"
          echo "Checking Runner.app in archive..."
          ls -la "$APP"

          rm -rf build/ios/unsigned
          mkdir -p build/ios/unsigned/Payload
          cp -R "$APP" build/ios/unsigned/Payload/

          cd build/ios/unsigned
          /usr/bin/zip -qry variphone_unsigned.ipa Payload

          echo "=== IPA created ==="
          ls -la variphone_unsigned.ipa

    artifacts:
      - build/ios/unsigned/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - ahmed.289ahmed@gmail.com
