workflows:
  ios-release:
    name: iOS IPA (Flutter build ipa) - variphone
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean & get packages
        script: |
          set -e
          flutter clean
          flutter pub get

      - name: Install CocoaPods (safe)
        script: |
          set -e
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build iOS IPA (release)
        script: |
          set -e
          flutter --version
          flutter build ipa --release

          echo "=== LIST build/ios/ipa ==="
          ls -la build/ios/ipa || true

          echo "=== FIND IPA ==="
          find build/ios -maxdepth 4 -type f -name "*.ipa" -print || true

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - ahmed.289ahmed@gmail.com
