workflows:
  ios-release:
    name: iOS Unsigned IPA - variphone
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean & get packages
        script: |
          set -euo pipefail
          flutter clean
          flutter pub get

      - name: (Optional) CocoaPods install
        script: |
          set -euo pipefail
          if [ -d "ios" ] && [ -f "ios/Podfile" ]; then
            cd ios
            pod install
            cd ..
          fi

      - name: Build unsigned IPA (no codesign)
        script: |
          set -euo pipefail
          flutter build ipa --release --no-codesign

          echo "=== LIST build/ios ==="
          ls -la build/ios || true

          echo "=== LIST build/ios/ipa ==="
          ls -la build/ios/ipa || true

          echo "=== LIST build/ios/archive ==="
          ls -la build/ios/archive || true

          echo "=== FIND IPA ==="
          find build/ios -maxdepth 4 -type f -name "*.ipa" -print || true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/ipa/*.dSYM.zip

    publishing:
      email:
        recipients:
          - ahmed.289ahmed@gmail.com
